// example/example-vue/app.vue
<script setup>
import { FlowSlot } from '@flowover/vue';
</script>

<template>
  <main
    style="
      padding-top: 1rem;
      display: flex;
      flex-direction: column;
      align-items: center;
    "
  >
    <img src="/logo.svg" alt="logo" style="max-width: 48px" />

    <FlowSlot> </FlowSlot>
  </main>
</template>

<style>
html,
body {
  background-color: #131313;
  height: 100vh;
  overflow: hidden;
  margin: 0;
}
</style>

// example/example-react/src/app/page.tsx
'use client';

import { FlowSlot } from '@flowover/react';

export default function Home() {
  return (
    <main className="flex flex-col items-center pt-4">
      <img src="React-icon.svg" alt="logo" className="max-w-[48px]" />

      <FlowSlot as="a" name="test" href></FlowSlot>
    </main>
  );
}
